//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_PURCHASE_ORDER
    {
        public long PURCHASE_ORDER_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime SHIPPMENT_DATE { get; set; }
        public int QUANTITY { get; set; }
        public decimal NET_AMOUNT { get; set; }
        public decimal CASH_RELEASE { get; set; }
        public long VENDOR_ID { get; set; }
        public long RFQ_ID { get; set; }
        public string ORDER_STATUS { get; set; }
        public string SPECIAL_INSTRUCTIONS { get; set; }
        public bool ISACTIVE_FLAG { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDWHEN { get; set; }
        public Nullable<System.DateTime> MODIFIEDWHEN { get; set; }
    }
}
