//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_MENU_RIGHTS
    {
        public long MENU_RIGHTS_ID { get; set; }
        public long USER_ID { get; set; }
        public long MENU_ID { get; set; }
        public bool INSERTION_FLAG { get; set; }
        public bool UPDATION_FLAG { get; set; }
        public bool DELETION_FLAG { get; set; }
        public bool SELECTION_FLAG { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATEDWHEN { get; set; }
    }
}
