//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_GENERAL_LEDGER
    {
        public long LEDGER_ID { get; set; }
        public long ACCOUNT_LEVEL_THREE_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public string POST_REF { get; set; }
        public string INVOICE_ID { get; set; }
        public string JOURNAL_REF { get; set; }
        public decimal DEBIT { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDWHEN { get; set; }
        public Nullable<System.DateTime> MODIFIEDWHEN { get; set; }
    }
}
