//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_SYS_TRANSACTION_LOG
    {
        public long SNO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public int ACTIVITY_CODE { get; set; }
        public string ACTIVITY_ON { get; set; }
        public int UPDATER_ID { get; set; }
        public Nullable<System.DateTime> UPDATER_DATETIME { get; set; }
        public string REMARKS { get; set; }
        public string ACTION { get; set; }
        public string REFERENCE_NAME { get; set; }
        public string REFERENCE_VALUES { get; set; }
        public string FIELD_NAMES { get; set; }
        public string FIELD_OLD_VALUES { get; set; }
        public string FIELD_NEW_VALUES { get; set; }
        public string UPDATE_PREVIOUS_DATETIME { get; set; }
        public string CHANGES_IN { get; set; }
    }
}
