//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_DISPLAY_STOCK
    {
        public long DSTOCK_ID { get; set; }
        public string DSTOCK_CODE { get; set; }
        public long BRANCH_ID { get; set; }
        public string SALE_CODE { get; set; }
        public System.DateTime DATE { get; set; }
        public long PRODUCT_ID { get; set; }
        public Nullable<int> QUANTITY_IN { get; set; }
        public Nullable<int> QUANTITY_OUT { get; set; }
        public string STOCK_TYPE { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public decimal TOTAL_PRICE { get; set; }
        public string WV_SHIPPMENT_CODE { get; set; }
        public string SHIPPMENT_FROM { get; set; }
        public Nullable<long> WSTOCK_CODE { get; set; }
        public bool ISMANUAL_ENTRY { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDWHEN { get; set; }
        public Nullable<System.DateTime> MODIFIEDWHEN { get; set; }
    }
}
