//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_USER_SESSION
    {
        public long USER_SESSION_ID { get; set; }
        public long USER_ID { get; set; }
        public Nullable<int> COUNTER_ID { get; set; }
        public System.DateTime LOGIN_DATETIME { get; set; }
        public short ISSUCCESS_LOGIN_FLAG { get; set; }
        public string IP_ADDRESS { get; set; }
        public Nullable<System.DateTime> LOGOUT_DATETIME { get; set; }
        public Nullable<short> ISSUCCESS_LOGOUT_FLAG { get; set; }
    }
}
