//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_SUPERVISOR
    {
        public long SUPERVISOR_ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string NIC { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<long> BRANCH_ID { get; set; }
        public Nullable<long> WEARHOUSE_ID { get; set; }
        public long CITY_ID { get; set; }
        public long STATE_ID { get; set; }
        public Nullable<long> COUNTRY_ID { get; set; }
        public bool ISACTIVE_FLAG { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDWHEN { get; set; }
        public Nullable<System.DateTime> MODIFIEDWHEN { get; set; }
    }
}
