//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_PRODUCT
    {
        public long PRODUCT_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_DESC { get; set; }
        public long PROFIT_MARGIN_RATE { get; set; }
        public decimal PAYBLE_PRICE { get; set; }
        public bool IS_TAX_APPLIED_FLAG { get; set; }
        public Nullable<int> TAX_PER { get; set; }
        public Nullable<decimal> TAX_RS { get; set; }
        public long TYPE_ID { get; set; }
        public long CATEGORY_ID { get; set; }
        public long UNIT_ID { get; set; }
        public Nullable<System.DateTime> EXPIRY_FROM { get; set; }
        public Nullable<System.DateTime> EXPIRY_TO { get; set; }
        public bool ISACTIVE_FLAG { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDWHEN { get; set; }
        public Nullable<System.DateTime> MODIFIEDWHEN { get; set; }
    }
}
