//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_PAYMENT_DETAIL
    {
        public long PAYMENT_ID { get; set; }
        public string CODE { get; set; }
        public string PAYMENT_DESC { get; set; }
        public long BANK_ID { get; set; }
        public long BANK_BRANCH_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string ACCOUNT_DESC { get; set; }
        public long PAYMENT_TYPE_ID { get; set; }
        public int TRANSACTION_NO { get; set; }
        public System.DateTime DATE { get; set; }
        public long PURCHASE_ORDER_ID { get; set; }
        public decimal AMOUNT { get; set; }
        public string AMOUNT_IN_WORDS { get; set; }
        public short ISTAXABLE_FLAG { get; set; }
        public short ISCASH_TRANSFERRED { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
        public bool ISACTIVE_FLAG { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDWHEN { get; set; }
        public Nullable<System.DateTime> MODIFIEDWHEN { get; set; }
    }
}
