//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_CUSTOMER_PROMOTIONS
    {
        public long CUSTOMER_PROMOTION_ID { get; set; }
        public long PROMOTION_ID { get; set; }
        public string AMOUNT_LEVEL { get; set; }
        public string DISCOUNT_TYPE { get; set; }
        public string DISCOUNT_VALUE { get; set; }
        public short IS_LUCKYDRAW_FLAG { get; set; }
        public string STATUS { get; set; }
        public long LUCKYDRAW_ID { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
        public string CREATEDBY { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDWHEN { get; set; }
        public Nullable<System.DateTime> MODIFIEDWHEN { get; set; }
    }
}
