//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_MENU
    {
        public long MENU_ID { get; set; }
        public short ILEVEL { get; set; }
        public short MASTER_MENU_ID { get; set; }
        public string CONTROLLER { get; set; }
        public string ACTION { get; set; }
        public string FORM_NAME { get; set; }
        public bool ISACTIVE_FLAG { get; set; }
        public bool ISPOSTED_FLAG { get; set; }
    }
}
