//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeezTech.POS.Web.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_EXCEPTION_LOG
    {
        public long SNO { get; set; }
        public string EXCEPTION_LAYER { get; set; }
        public string SOURCE_LAYER { get; set; }
        public string STACKTRACE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string MEMBER_TYPE { get; set; }
        public string METHOD { get; set; }
        public string FORM { get; set; }
        public Nullable<System.DateTime> EXCEPTION_DATETIME { get; set; }
        public string CLIENT_IP { get; set; }
        public string EXCEPTION_TYPE { get; set; }
    }
}
